spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/awbd
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: users
        format_sql: true
  flyway:
    enabled: true
    schemas: users
    default-schema: users
    baseline-on-migrate: true
