spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/awbd
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: transactions
        format_sql: true
  flyway:
    enabled: true
    schemas: transactions
    default-schema: transactions
    baseline-on-migrate: true
